from src.FaceExtraction.face_extractor import FaceExtractor
from src.FaceExtraction.utils import *


if __name__ == "__main__":
    # Clear results, which were previously generated by model.
    delete_files_from_folder(folder='../../model_output/*')

    face_extractor = FaceExtractor(face_part_classifier_filepath="../../downloaded_models/face_part_classifier.pt")

    # Get path of selected image, which will be further processed.
    image_to_crop_filepath = chose_file()

    model_output = face_extractor.extract_face_from(image_to_crop_filepath)

    if isinstance(model_output, ModelOutputs):
        save_message("../../model_output/message.txt", model_output.value)
    else:
        save_image(model_output, "../../model_output/result_image.jpg")
